### ISSUE TITLE
Implement automated download function for h5ad using CURIE in matrix_file field

### ISSUE THREAD

**Issue by dosumis** [cellannotation/cas-tools#124]
We should have a separate download function, but also allow for automated download to be used with merge/split functions that use h5ad.

Download system needs to understand CURIEs used in matrix_file field.  We have the beginings of a library of CURIEs for these on the CAS repo.

**Comment by ubyndr** [comment]
I wanted to clarify the last sentence: "We have the beginnings of a library of CURIEs for these on the CAS repo." Could you please provide more details on what you mean by "the beginnings of a library"? Specifically, is there already a partial implementation available, or is this something that’s planned for the future? Any pointers to the relevant section in the CAS repo would also be helpful.
Additionally, could you confirm the latest format for matrix_file_id in the metadata? I want to make sure I'm aligning with the correct format for this issue.

**Comment by hkir-dev** [comment]
Initial version of the CURIEs library is here: https://github.com/cellannotation/cell-annotation-schema/blob/main/registry/registry.json
