### ISSUE TITLE
Support deriving CELL_IDs from CAS heirarchy

### ISSUE THREAD

**Issue by dosumis** [cellannotation/cas-tools#15]
For a simple hierarchy, we only need to store Cell_IDs for rank=0

**Comment by dosumis** [comment]
This functionality is needed in order to demo editing hierarchy (in TDT) --> showing results in AnnData.

Ultimately we may be able to do this with RDF autogenerate by LinkML (see for example).  A quick fix might be to generate a networkX object from annotation objects (accession -> has_parent accession) and query that.

**Comment by dosumis** [comment]
networkx based solution here: https://github.com/dosumis/nhp_basal_ganglia_taxonomy/blob/main/derive_cell_ids_from_hierarchy.ipynb

**Comment by hkir-dev** [comment]
Now flatten is deriving cell-ids from hierarchy: https://github.com/cellannotation/cas-tools/commit/ebc933940d22fd403cc5bb6044646b70858d8ff7

**Comment by dosumis** [comment]
We need merge to do this (too). Demo:
- CAS JSON with cell_ids on clusters (pre-prepare? although we need some story about where cell_ids come from)
- edit in TDT changing name & hierarchy.
- Run merge to AnnData  (requires merge to be able to calc cell_ids on the fly from hierarchy)
- View in CxG annotate 
- Demo displaying reports in notebook
