### ISSUE TITLE
Spreadsheet to Cell Annotation JSON Converter SPEC

### ISSUE THREAD

**Issue by ubyndr** [cellannotation/cas-tools#34]
# Spreadsheet to Cell Annotation JSON Converter

## Introduction
This tool is designed to convert spreadsheet/CSV files into a Cell Annotation JSON schema. The conversion process includes parsing metadata, raw data, and generating annotations based on specified rules.

## Input File Format

- **Metadata:** The input files should have a metadata section at the top, starting with a line prefixed by '#' to indicate the start of metadata parsing. Metadata fields should be defined in this section to guide the parser.

- **Raw Data:** Following the metadata section, raw data should be present for conversion into the JSON schema.

## Parsing Rules

1. **Metadata Parsing:**
   - The metadata section is identified by lines starting with '#'.
   - Metadata fields should match as closely as possible with the top level of the JSON schema.
   - Extracted metadata should be incorporated into the top level of the generated JSON schema.

2. **Ignoring Specific Rows:**
   - Rows with a "CELL LABELSET NAME" containing "cell_type" should be ignored during raw data parsing.

3. **Header Alignment:**
   - Every header in the raw data should align with the schema fields.
   - Headers should be included in the annotation section where they are specified in the schema.

4. **User Annotations:**
   - Fields in the raw data that are not part of the schema should be added as user annotations in the same level as other annotations.
   - Use the column names as field names for user annotations.

5. **CELL TYPE NAME Formatting:**
   - "CELL TYPE NAME" should not be capitalized unless in the form of "CD14-xxx T9-yyy."

6. **Required Fields:**
   - Retrieve and add as many required fields as possible from the input files.

## Output

The tool generates a Cell Annotation JSON schema based on the provided rules and input data.

**Comment by dosumis** [comment]
Aim: Specification for a simple specification for curation of Cell Annotation Schema (CAS) instances into tables and for converting these tables to CAS.  This should support the curation of additional metadata fields, not in the schema, as long as these don't stomp on existing keys.

CAS is specified in JSON schema and has a nested structure.  At the top level we have general metadata about the dataset - a set (list) of key:value pairs.  One level down, we have two types of objects that can mostly be represented as tables with literals or lists of literals as values: Annotations and labelsets.  In both cases, we could potentially go down one level to another table.

Choice:  multiple linked sheets vs what an we hack into a single sheet.  To choose, we really need decide how much of CAS we should support.

Suggestion:

Single sheet: support general metadata in a commented header + simple annotation objects (no nesting) in the main table.  

Header: 
- header rows are specified using an # at the start of the line (column 1)
- header content: key:value pairs are columns 1 & 2. (better to use ':' to separate as for YAML)
- key names - for all CAS fields, keys MUST match CAS metadata field names (see [markdown schema](https://github.com/cellannotation/cell-annotation-schema/blob/main/build/CAP_schema.md)).  Additional keys are allowed.  Metadata must include a specification of the version and flavour of CAS to use.   Version can be specified with the `cellannotation_schema_version` field. We need more schema work to develop a standard for specifying schema flavour (CAP etc). Which other keys are required depends on what's specified in the reference schema.
- Value restrictions:  as specified in the reference schema.
- List fields - separation character(s) = `, `  # Not ideal - would prefer`|` as `,` means we need to force TSV or quoted CSV. 
Table:
* The first non-commented row = the header row.  For all CAS annotation object fields, columns names MUST match CAS annotation object key names (see [markdown schema](https://github.com/cellannotation/cell-annotation-schema/blob/main/build/CAP_schema.md)).  Additional keys are allowed.
* Table content: As specified in the specified reference schema
- List fields - separation character(s) = `, `  # Not ideal - would prefer`|`

If we want to support more, e.g. labelset metadata, it needs to be in separate, linked tables.  Linked tables require some way to specify a link between tables (with google sheets, this could be a sheet link) and a linking key.  e.g. for labelsets, this should be the labelset name.

Relationship to CxG:

Where a dataset is on CellXGene, there is no need to associate CL terms manually.  This can be done automatically using Pandasaurus_CxG - which can associate CL terms with the most specific annotations, according to curation by lattice/CxG.   Trying to propagate this information manually (e.g. specifying the most specific CL term redundantly for all hierarchy levels), is error prone.

**Comment by dosumis** [comment]
CC @mfutey @evanbiederstedt

**Comment by dosumis** [comment]
Example of linking CL term to appropriate levels in hierarchy based annotation in CxG: 

Hierarchy of annotations from Sikema (Integrated lung dataset):
![image](https://github.com/cellannotation/cas-tools/assets/112839/8f4e9309-d2d4-4c6a-8163-42e01d8211c8)
Combined with CL annotations (composed_primarily_of is used where cell sets defined by author annotations and annotation with CL correspond exactly:
![image](https://github.com/cellannotation/cas-tools/assets/112839/2be7ea1d-9066-49ac-a96b-fb9835204ed2)

**Comment by ubyndr** [comment]
I've implemented this in https://github.com/cellannotation/cas-tools/blob/main/src/cas/spreadsheet_to_cas.py. We should test it, then we can close this one. cc @dosumis
