### ISSUE TITLE
CAS-Tools architecture

### ISSUE THREAD

**Issue by dosumis** [cellannotation/cas-tools#5]
High level sketch:

1. Command line runner script(s) should wrap functionality specified by methods/classes in the core lib and should be located/declared so that they seamlessly install as CL tools from PyPi. Fixed by #8 
2. Package lib as cas-tools.  Fixed by #8 
3. Distinct functions/methods: 
    - check and report on CAS-Anndata compatibility - see checks in: https://github.com/cellannotation/cas-tools/issues/6 
    - CAS->Anndata conversion:
        - Supports [full](https://github.com/cellannotation/cas-tools/pull/1) or partial (configurable) flattening with limit case being all info CAS apart from labelset:cell_label pairs being in 'uns' (see https://github.com/cellannotation/cas-tools/pull/4)
   - [ ] CAS writer - details TBD.
   - [x] CAS validator (imported from CAS)
   - [x] #11
        e.g. generate dataframe of annotation objects for some specified labelsets.
4. I'll leave open discussion of structuring classes - @hkir-dev & @ubyndr can you develop a proposal?

**Comment by evanbiederstedt** [comment]
@hkir-dev update on this?

**Comment by dosumis** [comment]
Closing this ticket as outdated. As you can see from the linked PRs most of this has been implemented. The CAS writer task is underspecified so can be ignored.  The only thing we don't have is configurable flattening.
