### ISSUE TITLE
"Module not found error" when trying to install cas-tools package

### ISSUE THREAD

**Issue by AvolaAmg** [cellannotation/cas-tools#54]
I had a few errors for installing the `cas-tools` package on pycharm. The modules `cellxgene_census` and `cas_schema` were not found. I installed `cellxgene_census` but I could not find `cas_schema`. Could you help ? 

Thanks!

 
<img width="450" alt="Screenshot 2024-03-15 at 15 58 43" src="https://github.com/cellannotation/cas-tools/assets/81253886/9d3f3bf2-61fe-4a44-9945-b280a1df0136">
<img width="398" alt="Screenshot 2024-03-15 at 15 58 35" src="https://github.com/cellannotation/cas-tools/assets/81253886/8c6e90ea-5590-4a11-bed5-c01d1678dc8c">

@ubyndr

**Comment by ubyndr** [comment]
How did you attempt to install the cas-tools package in PyCharm?

**Comment by AvolaAmg** [comment]
Thanks for your quick response. 
On the PyCharm command line I used `cas --help`. I used the python version 3.9. It was the first time I used it on this machine so the first thing I installed was just `cas-tools`, no other packages were present.

**Comment by ubyndr** [comment]
Did you use `pip install cas-tools`?

**Comment by AvolaAmg** [comment]
No I used the GUI: 
PyCharm settings>Project: pythonProject>Python Interpreter > + Package. and there it was giving errors.
![image](https://github.com/cellannotation/cas-tools/assets/81253886/fba0b327-943d-4c5c-afa0-2f6ffa7ca75e)

I just did it using `pip install cas-tools` and it works in that way. Thanks!
