### ISSUE TITLE
Populate Cell_IDs from AnnData

### ISSUE THREAD

**Issue by dosumis** [cellannotation/cas-tools#9]
A typical starting point for CAS is a table of annotation objects - which contain metadata about annotations in an AnnData file.  i.e.- the AnnData file is a reference for the Cell_IDs. 

It therefore makes sense to have an option to populate Cell-IDS in CAS from a linked AnnData file.  This would require checking that labelset names and values match between CAS and AnnData.  

Notes: 
 - This can be done simply as part of code running pre-load checks.  The alternative approach documented in notebooks is unnecessary. 
 - This is more complex if using a BICAN-style asserted hierarchy.  If pulling all cell IDs, one would have to check that the hierarchy matches.  Alternatively, only the most granular (rank 0) should have cell IDs pulled from AnnData with the CAS hierarchy considered the master.

Related ticket:

 - [ ] #10

**Comment by dosumis** [comment]
Wrote a quick python script for this as needed for pipelne testing:

```python

import anndata
import json
import sys

"""Add/update CellIDs to CAS from matching AnnData file"""

ad = anndata.read_h5ad(sys.argv[1], backed=True)  # path to anndata file
with open(sys.argv[2], 'r') as f:  # path to CAS JSON file
    j = json.loads(f.read())
ad_ranks = sys.argv[3].split(',')  # List of labelsets to update with IDs from AnnData

out = {}
for k,v in ad.obs.iterrows():
    for r in ad_ranks:
        val = v[r]
        if val:
            if not r in out.keys(): out[r] = {}
            if not val in out[r].keys(): out[r][val]=[]
            out[r][v[r]].append(k)

for a in j['annotations']:
    if not (a['labelset'] in out.keys()):
        print("Unknown labelset %s", (a['labelset']))
    elif not (a['cell_label']) in out[a['labelset']].keys():
        print("Unknown value %s in labelset %s", (a['cell_label'], a['labelset']))
    else:
        a['cell_ids']=out[a['labelset']][a['cell_label']]

with open(sys.argv[2], 'w') as f:
    f.write(json.dumps(j))

ad.file.close()
```

**Comment by hkir-dev** [comment]
As far as I understand this script expects a flattened AnnData as input.

I added a [populate_cell_ids script](https://github.com/cellannotation/cas-tools/blob/ctat_integration/src/cas/populate_cell_ids.py) that uses Ugur's edition that expects a standard AnnData file as input. This script has issues with handling multi-level hierarchies (rank > 2) but can be improved gradually.
